import { MenuItem } from './types';

export const MENU_ITEMS: MenuItem[] = [
  {
    id: '1',
    name: 'Volcanic Paneer Tikka',
    description: 'Fresh cottage cheese cubes marinated in ghost pepper sauce and hung yogurt, char-grilled in a clay oven.',
    price: 349,
    category: 'starters',
    image: 'https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?q=80&w=1000&auto=format&fit=crop',
    spicyLevel: 3,
    isPopular: true,
  },
  {
    id: '2',
    name: 'Smoked Butter Chicken',
    description: 'Tandoor-cooked chicken simmered in a rich, buttery tomato satin gravy with a hint of fenugreek.',
    price: 449,
    category: 'mains',
    image: 'https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?q=80&w=1000&auto=format&fit=crop',
    spicyLevel: 1,
    isPopular: true,
  },
  {
    id: '3',
    name: 'Royal Saffron Biryani',
    description: 'Long-grain basmati rice Dum-cooked with aromatic spices, saffron strands, and caramelized onions.',
    price: 399,
    category: 'mains',
    image: 'https://images.unsplash.com/photo-1589302168068-964664d93dc0?q=80&w=1000&auto=format&fit=crop',
    spicyLevel: 2,
  },
  {
    id: '4',
    name: 'Crispy Masala Corn',
    description: 'Golden fried corn kernels tossed with onions, peppers, and our secret tangy spice mix.',
    price: 249,
    category: 'starters',
    image: 'https://images.unsplash.com/photo-1620589125156-fd5028c5e05b?q=80&w=1000&auto=format&fit=crop',
    spicyLevel: 1,
  },
  {
    id: '5',
    name: 'Mango & Cardamom Mousse',
    description: 'Silky mango mousse infused with fresh cardamom, topped with pistachio crumble.',
    price: 199,
    category: 'desserts',
    image: 'https://images.unsplash.com/photo-1563729784474-d77dbb933a9e?q=80&w=1000&auto=format&fit=crop',
    spicyLevel: 0,
  },
  {
    id: '6',
    name: 'Electric Lime Mojito',
    description: 'Fresh lime, mint, and soda with a splash of electric green syrup and chaat masala.',
    price: 149,
    category: 'drinks',
    image: 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?q=80&w=1000&auto=format&fit=crop',
    spicyLevel: 0,
  },
  {
    id: '7',
    name: 'Firecracker Prawns',
    description: 'Tiger prawns stir-fried with Szechuan peppers, curry leaves, and dried red chilies.',
    price: 549,
    category: 'starters',
    image: 'https://images.unsplash.com/photo-1625937751876-4515cd8e7c4f?q=80&w=1000&auto=format&fit=crop',
    spicyLevel: 3,
  },
  {
    id: '8',
    name: 'Tandoori Lamb Chops',
    description: 'Succulent lamb chops marinated in yogurt and spices, roasted to perfection in a clay oven.',
    price: 699,
    category: 'mains',
    image: 'https://images.unsplash.com/photo-1544025162-d76694265947?q=80&w=1000&auto=format&fit=crop',
    spicyLevel: 2,
    isPopular: true,
  },
  {
    id: '9',
    name: 'Gulab Jamun Cheesecake',
    description: 'Fusion dessert combining classic Gulab Jamun with a creamy NY cheesecake base.',
    price: 229,
    category: 'desserts',
    image: 'https://images.unsplash.com/photo-1589119908995-c6837fa14848?q=80&w=1000&auto=format&fit=crop',
    spicyLevel: 0,
  },
];

export const CATEGORIES: { id: string; label: string }[] = [
  { id: 'all', label: 'All' },
  { id: 'starters', label: 'Starters' },
  { id: 'mains', label: 'Mains' },
  { id: 'desserts', label: 'Desserts' },
  { id: 'drinks', label: 'Drinks' },
];